"""Add aura_multiplier to Product table

Revision ID: e0bef348793c
Revises:
Create Date: 2025-08-17 06:41:14.305988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0bef348793c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aura_multiplier', sa.Float(), server_default='3.0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('aura_multiplier')

    # ### end Alembic commands ###
